name: Greetings from GitHub Actions

on: 
    workflow_dispatch:

jobs:
    placeholder:
        name: Display Greetings
        runs-on: ubuntu-24.04
        steps:
            - name: Say Hello
              run: |
                echo "Hello World!"