name: Greetings from GitHub Actions

on: 
    workflow_dispatch:

jobs:
    greetings:
        name: Display Greetings
        runs-on: ubuntu-24.04
        steps:
            - name: Say Hello
              run: |
                echo "Hello World!"
            - name: Si Hola
              run: |
                echo "¡Hola Mundo!"