name: On Push to Feature Branch

on:
    push:
        branches:
            - '**'
            - '!main'

jobs:
    feature-branch-push:
        name: Feature Push
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Get the next semantic version for the repo
              id: next_semantic
              uses: paulhatch/semantic-version@v5.4.0

            - name: Show outputs
              run: | 
                echo "next_semantic_version=${{steps.next_semantic.outputs.version_tag}}"